#실사용 용도
server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: heoth
    password: 1234

mybatis:
  config-location: classpath:mapper/config/config.xml
  mapper-locations: classpath:mapper/sql/**/*.xml